### ISSUE TITLE
WPS Office has not found any installed printers.

### ISSUE THREAD

**Issue by llcool** [cyrpaut/wps-office-all-lang-no-internet#1]
If you get this message "WPS Office has not found any installed printers." and you have at lease one printer installed, run this command:
sudo snap connect wps-office-all-lang-no-internet:cups-control :cups-control

**Comment by cyrpaut** [comment]
Hello,
Thank you for reporting this issue. Indeed I have noticed it and found this command. This is a mistery for me why the permission is asked in the config file, understood by snapd daemon but the slot is not properly connected. If you have a clue why I'll fix the problem. Thanks

**Comment by WillParryRussia** [comment]
And I got : 
snap "wps-office-all-lang-no-internet" has no plug named "cups-control"

**Comment by paulkastel** [comment]
Depend on which wps version you got installed you need to use different version of command. For me worked:
`sudo snap connect wps-office-multilang:cups-control :cups-control`

**Comment by cyrpaut** [comment]
Hello,
For some reasons, CUPS is disables by default when you build a snap, for security reasons.
See: https://ubuntu.com/blog/a-guide-to-snap-permissions-and-interfaces
Therefore, you need to enable it manually.

**Comment by dmaglio** [comment]
what if it was installed from rpm files (like I did on Fedora 31)?

**Comment by krystalsavage** [comment]
I've installed and updated Fedora 32 and seem to have an issue with WPS Office. Runs beautifully and imports both microsoft templates as well as my documents written in office 365. Unfortunately, I get an error when i go to print:  "Unable to find cups library, please make sure it's installed." And in the SYSTEM CHECK window that pops up ... the error is stated there as well: Missing Cups libraries. Cannot access the printer. WPS Office has worked flawlessly over the past few years. Until this new version "11.1.0.9505" WPS Office 2019. How am I going to print?

**Comment by tclahr** [comment]
I am running WPS 11.1.0.9719 on a Fedora 33 system and I have the same missing cups libraries issue.
WPS was installed using the RPM package. I am not running it using snap.

![image](https://user-images.githubusercontent.com/20645243/101174041-1a1f9f00-3622-11eb-8db1-fbd6ea2d99e3.png)

**Comment by mgogala** [comment]
That is the software problem. LibreOffice finds my printer without problems. The vendor is really dragging this issue through several months. I removed WPS office and am relying on LibreOffice 7.0.4. So far, no problems.

**Comment by JoseLuisAza** [comment]
![Captura de pantalla de 2021-05-04 10-36-56](https://user-images.githubusercontent.com/26821255/117038285-afec5280-acc4-11eb-9102-8820efda1deb.png)
darle los permisos en la tienda para la impresora

**Comment by mt190502** [comment]
> I am running WPS 11.1.0.9719 on a Fedora 33 system and I have the same missing cups libraries issue.
> WPS was installed using the RPM package. I am not running it using snap.
> 
> ![image](https://user-images.githubusercontent.com/20645243/101174041-1a1f9f00-3622-11eb-8db1-fbd6ea2d99e3.png)

This problem occurs in me. I am using Fedora. And downloaded the rpm package. But I get a warning that the cups library is missing. I installed these packages of Cups;
cups-client
python3-cups
cups-ipptool
cnrdrvcups-ufr2-uk
cups-libs
cups-filesystem
cups-filters-libs
cups-filters
cups
cups-lpd
cups-pk-helper

How can i fix this problem?

**Comment by iJeane** [comment]
> what if it was installed from rpm files (like I did on Fedora 31)?

I have installed the snap version first...
`sudo snap install wps-2019-snap`
then run this command
`sudo snap connect wps-2019-snap:cups-control :cups-control`
then run WPS, accept EULA and test printing. If it works but you want the latest version installed, uninstall WPS snap
`sudo snap remove wps-2019-snap`
then download the latest version of WPS from [this link](https://www.wps.com/office/linux) and install it
**Note:** If you cannot access the website... try using VPN
`sudo dnf install <wps_file...rpm>`
I don't know how but the missing cups error is fixed and I can print with the latest version

![Screenshot from 2022-04-20 00-06-09](https://user-images.githubusercontent.com/31350665/164047377-821f3942-274e-4c44-83f2-6e704f54d5d2.png)

**Comment by tangruize** [comment]
It seems that this cmd solves the problem ([link](http://cache.baiducontent.com/c?m=_Q9MiUuBxYqtar2_rOZyt4xPOXKI3OBFysdC83Rwoz2kI5xqXV_0LN33HSKceoaXsqc9etg9t0GwMxQSf-sVuG35UqFAK1jcZEuEFDqOo-u29D4AqxEHOij2pcdX53r3GP_agQwC-4syOcXuCmPBYOxnhPr6jpQqhrl5kcx72tG&p=8b2a97009f8302dd17bd9b7d0b17cf&newp=c4759a46d0c257fc57efc66d174a8d231610db2151d3d4136b82c825d7331b001c3bbfb422201a0ed3c4796504af4d59e0f13c77330923a3dda5c91d9fb4c574799e&s=c9f0f895fb98ab91&user=baidu&fm=sc&query=wps+linux+cups%BF%E2%D5%D2%B2%BB%B5%BD&qid=d529790b002aa4aa&p1=8#:~:text=sudo%20rm%20%2Df%20/opt/kingsoft/wps%2Doffice/office6/libssl.so*%20/opt/kingsoft/wps%2Doffice/office6/libcrypto.so*)):
```
sudo rm -f /opt/kingsoft/wps-office/office6/libssl.so* /opt/kingsoft/wps-office/office6/libcrypto.so*
```

**Comment by reddof** [comment]
> > I am running WPS 11.1.0.9719 on a Fedora 33 system and I have the same missing cups libraries issue.
> > WPS was installed using the RPM package. I am not running it using snap.
> > ![image](https://user-images.githubusercontent.com/20645243/101174041-1a1f9f00-3622-11eb-8db1-fbd6ea2d99e3.png)
> 
> This problem occurs in me. I am using Fedora. And downloaded the rpm package. But I get a warning that the cups library is missing. I installed these packages of Cups; cups-client python3-cups cups-ipptool cnrdrvcups-ufr2-uk cups-libs cups-filesystem cups-filters-libs cups-filters cups cups-lpd cups-pk-helper
> 
> How can i fix this problem?

I use both of Arch and Artix, I have the same problem "missing cups libraries". In arch this problem solved with install lib32-libcups ( or something like that ) , but in Artix this lib32 does not solve the problem.
